<?php

namespace StudentBundle\Repository;

/**
 * studentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class studentRepository extends \Doctrine\ORM\EntityRepository
{
}
