<?php

namespace StudentBundle\Repository;

/**
 * studentmarksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class studentmarksRepository extends \Doctrine\ORM\EntityRepository
{
}
